name: Full Auto Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Go App
        run: |
          go build -v -o myapp ./cmd

      - name: Prepare and Copy Binary
        run: |
          sudo systemctl stop fitness.service
          rm -f /root/tension/myapp
          cp myapp /root/tension/myapp
          chmod +x /root/tension/myapp

      - name: Start Service
        run: sudo systemctl start fitness.service

      - name: Check Status
        run: systemctl status fitness.service
      