name: Full Auto Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Go App
        run: |
          # Собираем бинарник. Убедись, что путь ./cmd верный.
          go build -v -o myapp ./cmd 

      - name: Prepare and Copy Binary
        run: |
          # 1. Останавливаем сервис fitness
          sudo systemctl stop fitness.service
          
          # 2. Удаляем старый и копируем новый файл
          rm -f /root/tension/myapp
          cp myapp /root/tension/myapp
          
          # 3. Права на запуск
          chmod +x /root/tension/myapp

      - name: Start Service
        run: sudo systemctl start fitness.service

      - name: Check Status
        run: systemctl status fitness.service